# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MessagingApp' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MessagingApp

pod 'Firebase/Database'
     pod 'Firebase/Auth'
     pod 'Firebase/Storage'
     pod 'ProgressHUD'
     pod 'SDWebImage', '~>4.0'
     pod 'Firebase/Core'
     pod 'Firebase/Messaging'

  target 'MessagingAppTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'Firebase/Database'
    pod 'Firebase/Auth'
    pod 'Firebase/Storage'
    
  end

  target 'MessagingAppUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
